/*
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = YNAB.SDK.Client.OpenAPIDateConverter;

namespace YNAB.SDK.Model
{
    /// <summary>
    /// BudgetSettings
    /// </summary>
    [DataContract(Name = "BudgetSettings")]
    public partial class BudgetSettings : IEquatable<BudgetSettings>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BudgetSettings" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BudgetSettings() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BudgetSettings" /> class.
        /// </summary>
        /// <param name="dateFormat">dateFormat (required).</param>
        /// <param name="currencyFormat">currencyFormat (required).</param>
        public BudgetSettings(DateFormat dateFormat = default(DateFormat), CurrencyFormat currencyFormat = default(CurrencyFormat))
        {
            // to ensure "dateFormat" is required (not null)
            this.DateFormat = dateFormat ?? throw new ArgumentNullException("dateFormat is a required property for BudgetSettings and cannot be null");
            // to ensure "currencyFormat" is required (not null)
            this.CurrencyFormat = currencyFormat ?? throw new ArgumentNullException("currencyFormat is a required property for BudgetSettings and cannot be null");
        }

        /// <summary>
        /// Gets or Sets DateFormat
        /// </summary>
        [DataMember(Name = "date_format", IsRequired = true, EmitDefaultValue = false)]
        public DateFormat DateFormat { get; set; }

        /// <summary>
        /// Gets or Sets CurrencyFormat
        /// </summary>
        [DataMember(Name = "currency_format", IsRequired = true, EmitDefaultValue = false)]
        public CurrencyFormat CurrencyFormat { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BudgetSettings {\n");
            sb.Append("  DateFormat: ").Append(DateFormat).Append("\n");
            sb.Append("  CurrencyFormat: ").Append(CurrencyFormat).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BudgetSettings);
        }

        /// <summary>
        /// Returns true if BudgetSettings instances are equal
        /// </summary>
        /// <param name="input">Instance of BudgetSettings to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BudgetSettings input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.DateFormat == input.DateFormat ||
                    (this.DateFormat != null &&
                    this.DateFormat.Equals(input.DateFormat))
                ) && 
                (
                    this.CurrencyFormat == input.CurrencyFormat ||
                    (this.CurrencyFormat != null &&
                    this.CurrencyFormat.Equals(input.CurrencyFormat))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.DateFormat != null)
                    hashCode = hashCode * 59 + this.DateFormat.GetHashCode();
                if (this.CurrencyFormat != null)
                    hashCode = hashCode * 59 + this.CurrencyFormat.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
