/* 
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = YNAB.SDK.Client.OpenAPIDateConverter;

namespace YNAB.SDK.Model
{
    /// <summary>
    /// MonthSummariesResponseData
    /// </summary>
    [DataContract]
    public partial class MonthSummariesResponseData :  IEquatable<MonthSummariesResponseData>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MonthSummariesResponseData" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MonthSummariesResponseData() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MonthSummariesResponseData" /> class.
        /// </summary>
        /// <param name="months">months (required).</param>
        /// <param name="serverKnowledge">The knowledge of the server (required).</param>
        public MonthSummariesResponseData(List<MonthSummary> months = default(List<MonthSummary>), long serverKnowledge = default(long))
        {
            // to ensure "months" is required (not null)
            if (months == null)
            {
                throw new InvalidDataException("months is a required property for MonthSummariesResponseData and cannot be null");
            }
            else
            {
                this.Months = months;
            }

            // to ensure "serverKnowledge" is required (not null)
            if (serverKnowledge == null)
            {
                throw new InvalidDataException("serverKnowledge is a required property for MonthSummariesResponseData and cannot be null");
            }
            else
            {
                this.ServerKnowledge = serverKnowledge;
            }

        }
        
        /// <summary>
        /// Gets or Sets Months
        /// </summary>
        [DataMember(Name="months", EmitDefaultValue=false)]
        public List<MonthSummary> Months { get; set; }

        /// <summary>
        /// The knowledge of the server
        /// </summary>
        /// <value>The knowledge of the server</value>
        [DataMember(Name="server_knowledge", EmitDefaultValue=false)]
        public long ServerKnowledge { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MonthSummariesResponseData {\n");
            sb.Append("  Months: ").Append(Months).Append("\n");
            sb.Append("  ServerKnowledge: ").Append(ServerKnowledge).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MonthSummariesResponseData);
        }

        /// <summary>
        /// Returns true if MonthSummariesResponseData instances are equal
        /// </summary>
        /// <param name="input">Instance of MonthSummariesResponseData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MonthSummariesResponseData input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Months == input.Months ||
                    this.Months != null &&
                    input.Months != null &&
                    this.Months.SequenceEqual(input.Months)
                ) && 
                (
                    this.ServerKnowledge == input.ServerKnowledge ||
                    this.ServerKnowledge.Equals(input.ServerKnowledge)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Months != null)
                    hashCode = hashCode * 59 + this.Months.GetHashCode();
                hashCode = hashCode * 59 + this.ServerKnowledge.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
